version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8081:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/opt/certs
      # - ./data:/data